<a href="https://colab.research.google.com/github/khushi2068/NumPyAssignment/blob/main/NumPy_Ass_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy


In [28]:
import numpy as np

#### a)Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [29]:


arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = np.flip(arr)

print(reversed_arr)


[5 4 6 3 2 1]


b)Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [37]:
 array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
 print(array1)
flatten_arr=np.ravel(array1)
print(flatten_arr)

[[1 2 3]
 [2 4 5]
 [1 2 3]]
[1 2 3 2 4 5 1 2 3]


c)Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [10]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
is_equal=np.array_equal(arr1, arr2)
print(is_equal)

True


d)Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [25]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
a=np.bincount(x).argmax()
b=np.bincount(y).argmax()
print(a)
print('indexes')
for i in range(len(x)):
  if x[i]==a:
            print(i,end=' ');

print()

print(b)
print('indexes')
for i in range(len(y)):
  if y[i]==b:
            print(i,end=' ');



1
indexes
0 5 7 8 9 
1
indexes
0 1 2 

e)For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [27]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

#  Sum of all elements
total_sum = np.sum(gfg)

# Sum of all elements row-wise
row_sums = np.sum(gfg, axis=1)

# Sum of all elements column-wise
column_sums = np.sum(gfg, axis=0)

print("Sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_sums)
print("Sum of all elements column-wise:", column_sums)


Sum of all elements: 45 Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


f)) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [36]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Sum of diagonal elements:", np.trace(n_array))
# print("Eigenvalues of matrix:", np.linalg.eigvals(n_array))

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues of matrix:\n", eigenvalues)
print("Eigenvectors of matrix:\n", eigenvectors)

print("Inverse of matrix:\n", np.linalg.inv(n_array))
print("Determinant of matrix:\n", np.linalg.det(n_array))

Sum of diagonal elements: 176
Eigenvalues of matrix:
 [98.16835147 28.097044   49.73460452]
Eigenvectors of matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix:
 137180.0000000001


g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]


In [51]:
 p = [[1, 2], [2, 3]]
 q = [[4, 5], [6, 7]]
 m1=np.dot(p,q)
 print(m1)
 print(np.cov(p,q))
 print()
 r =np.array( [[1, 2], [2, 3], [4, 5]] )
 s = np.array([[4, 5, 1], [6, 7, 2]])
 m2=np.dot(r,s)
 print(m2)
 p_vector=r.flatten()
 q_vector=s.flatten()
 print(np.cov(p_vector,q_vector))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


h)For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [54]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


Q2: Based on NumPy Mathematics and Statistics
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row


In [58]:


array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
absolute_value = np.abs(array)

# ii. Percentiles for each column and each row
percentiles_column = np.percentile(array, q=[25, 50, 75], axis=0)
percentiles_row = np.percentile(array, q=[25, 50, 75], axis=1)

# iii. Mean, Median, and Standard Deviation for each column, each row, and flattened array
mean_column = np.mean(array, axis=0)
mean_row = np.mean(array, axis=1)
mean_flattened = np.mean(array.flatten())
median_column = np.median(array, axis=0)
median_row = np.median(array, axis=1)
median_flattened = np.median(array.flatten())
std_column = np.std(array, axis=0)
std_row = np.std(array, axis=1)
std_flattened = np.std(array.flatten())

print("Element-wise absolute value:")
print(absolute_value)

print("25th, 50th, and 75th percentile for each column:")
print(percentiles_column)
print("25th, 50th, and 75th percentile for each row:")
print(percentiles_row)

print("Mean for each column:")
print(mean_column)
print("Mean for each row:")
print(mean_row)
print("Mean of flattened array:")
print(mean_flattened)

print("Median for each column:")
print(median_column)
print("Median for each row:")
print(median_row)
print("Median of flattened array:")
print(median_flattened)

print("Standard Deviation for each column:")
print(std_column)
print("Standard Deviation for each row:")
print(std_row)
print("Standard Deviation of flattened array:")
print(std_flattened)


Element-wise absolute value:
[[1 2 3]
 [4 5 6]]
25th, 50th, and 75th percentile for each column:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
25th, 50th, and 75th percentile for each row:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean for each column:
[-1.5  1.5 -1.5]
Mean for each row:
[ 0.66666667 -1.66666667]
Mean of flattened array:
-0.5
Median for each column:
[-1.5  1.5 -1.5]
Median for each row:
[ 1. -4.]
Median of flattened array:
-0.5
Standard Deviation for each column:
[2.5 3.5 4.5]
Standard Deviation for each row:
[2.05480467 4.78423336]
Standard Deviation of flattened array:
3.8622100754188224


For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [60]:
 a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
 print(np.floor(a))
 print(np.ceil(a))
 print(np.trunc(a))
 print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements


---



In [61]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
indices_sorted = np.argsort(array)
smallest_elements = sorted_array[:4]
largest_elements = sorted_array[-5:]

print("Sorted array:")
print(sorted_array)

print("Indices of sorted array:")
print(indices_sorted)

print("4 smallest elements:")
print(smallest_elements)

print("5 largest elements:")
print(largest_elements)


Sorted array:
[ 10  16  16  52  54  62 453]
Indices of sorted array:
[0 3 4 1 5 2 6]
4 smallest elements:
[10 16 16 52]
5 largest elements:
[ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only


In [62]:
import numpy as np

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[array.astype(int) == array]
float_elements = array[array.astype(int) != array]

print("Integer elements only:")
print(integer_elements)

print("Float elements only:")
print(float_elements)


Integer elements only:
[1. 2. 3. 2.]
Float elements only:
[1.2 2.2]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)
(b) Load the saved file into jupyter notebook?

---



In [70]:
from PIL import Image
img=Image.open("/1746841.png")
narr=np.array(img)
np.savetxt('/content/sample_data/textfile.txt', array, fmt='%d')

In [73]:
import cv2
import numpy as np

def img_to_array(path):
    image = cv2.imread(path)
    np.savetxt('/content/sample_data/k.txt', image.flatten(), fmt='%d')

# Call the function with the image path
img_to_array('/1746841.png')


In [ ]:
# Define the file path
file_path = '/content/sample_data/textfile.txt'

# Open the file in read mode and read its content
with open(file_path, 'r') as file:
    content = file.read()

# Print the content of the file
print(content)
